// Falas fixas da "IA" no roteiro da apresentação "CX Preditivo — IA LAB".
// Clicar em uma linha faz o avatar falar exatamente esse texto (sem passar pelo LLM).
export const SCRIPT = [
  {
    slide: "Slide 2",
    title: "Apresentando a IA",
    cue: "Ana: “Vamos apresentar a nossa terceira integrante.”",
    text: "Olá, pessoal. Eu sou a Rogéria.",
  },
  {
    slide: "Slide 2",
    title: "Sugestão de nome",
    cue: "Ana: “Ela ainda não tem nome.”",
    text: "Posso sugerir um?",
  },
  {
    slide: "Slide 2",
    title: "Otimizando o processo",
    cue: "Nubya: “Já começou querendo mandar na apresentação.”",
    text: "Estou apenas tentando otimizar o processo.",
  },
  {
    slide: "Slide 3",
    title: "Chegando depois",
    cue: "Ana: “Mas existe uma questão.”",
    text: "Vocês estão sempre chegando depois.",
  },
  {
    slide: "Slide 3",
    title: "Não foi crítica",
    cue: "Ana: “Obrigada pela delicadeza.”",
    text: "Não foi uma crítica. Foi uma análise.",
  },
  {
    slide: "Slide 4",
    title: "A pergunta certa",
    cue: "Nubya: “Começamos a perguntar... O que pode acontecer?”",
    text: "E principalmente... o que podemos fazer antes que aconteça?",
  },
  {
    slide: "Slide 5",
    title: "Próximo capítulo",
    cue: "Ana: “Em outras palavras...”",
    text: "É tentar descobrir o próximo capítulo antes dele acontecer.",
  },
  {
    slide: "Slide 5",
    title: "Frases de efeito",
    cue: "Ana: “Eu também.”",
    text: "Eu posso fazer frases de efeito.",
  },
  {
    slide: "Slide 6",
    title: "Infelizmente",
    cue: "Ana: “Isso não significa que a IA está lendo a mente do cliente.”",
    text: "Infelizmente.",
  },
  {
    slide: "Slide 6",
    title: "Mais fácil",
    cue: "Nubya: “Infelizmente?”",
    text: "Seria muito mais fácil.",
  },
  {
    slide: "Slide 6",
    title: "Identificando padrões",
    cue: "(retomando a explicação)",
    text: "Eu trabalho identificando padrões. Por exemplo: histórico de contatos, comportamento, tempo de espera, recorrência, sentimento, produtos, pedidos e diversos outros sinais.",
  },
  {
    slide: "Slide 6",
    title: "Probabilidade",
    cue: "Ana: “E quando esses sinais começam a se repetir...”",
    text: "Eu consigo identificar uma probabilidade.",
  },
  {
    slide: "Slide 7",
    title: "Novo contato",
    cue: "Ana: “O que vocês acham que pode acontecer?”",
    text: "Eu apostaria em um novo contato.",
  },
  {
    slide: "Slide 7",
    title: "Cancelamento",
    cue: "Ana: “E talvez?”",
    text: "Cancelamento.",
  },
  {
    slide: "Slide 7",
    title: "Baseado em padrões",
    cue: "Nubya: “E como você chegou nessa conclusão?”",
    text: "Não foi uma previsão aleatória. Foi baseada nos padrões de comportamento.",
  },
  {
    slide: "Slide 8",
    title: "Agir antes",
    cue: "Nubya: “No modelo preditivo, podemos identificar sinais antes.”",
    text: "E agir antes que uma pequena frustração se transforme em uma grande reclamação.",
  },
  {
    slide: "Slide 9",
    title: "Dando sinais",
    cue: "Ana: “Não abriu chamado. Não mandou mensagem. Nada.”",
    text: "Mesmo assim, ele pode estar dando sinais.",
  },
  {
    slide: "Slide 9",
    title: "Probabilidade, não certeza",
    cue: "Ana: “Então você está dizendo que podemos identificar um cliente insatisfeito antes dele reclamar?”",
    text: "Não necessariamente identificar a insatisfação com 100% de certeza. Mas podemos identificar uma probabilidade maior de insatisfação ou de um novo contato.",
  },
  {
    slide: "Slide 10",
    title: "Eu consigo",
    cue: "Ana: “Uma pessoa sozinha não conseguiria analisar todos esses comportamentos.”",
    text: "Eu consigo.",
  },
  {
    slide: "Slide 10",
    title: "Característica estatística",
    cue: "Nubya: “Convencida.”",
    text: "É apenas uma característica estatística.",
  },
  {
    slide: "Slide 11",
    title: "Vai substituir?",
    cue: "Ana: “Ela vai substituir o atendimento?”",
    text: "Não.",
  },
  {
    slide: "Slide 11",
    title: "Identificar x resolver",
    cue: "Ana: “Resposta rápida.”",
    text: "Porque identificar um problema não significa saber resolver um problema.",
  },
  {
    slide: "Slide 11",
    title: "Pessoa ainda essencial",
    cue: "Nubya: “Boa.”",
    text: "Eu posso identificar que um cliente provavelmente está frustrado. Mas uma pessoa ainda pode ser essencial para decidir qual é a melhor forma de agir.",
  },
  {
    slide: "Slide 12",
    title: "Interessante",
    cue: "Ana: “Olha quantas possibilidades.” (após respostas do público)",
    text: "Interessante.",
  },
  {
    slide: "Slide 12",
    title: "Algo em comum",
    cue: "Nubya: “Por quê?”",
    text: "Porque todas essas respostas têm algo em comum.",
  },
  {
    slide: "Slide 12",
    title: "Antes de acontecer",
    cue: "Ana: “O quê?”",
    text: "Vocês querem descobrir o que vai acontecer antes de acontecer.",
  },
  {
    slide: "Slide 13",
    title: "Antecipar",
    cue: "Ana: “Identificar padrões.”",
    text: "Antecipar.",
  },
  {
    slide: "Slide 13",
    title: "Agir antes",
    cue: "Nubya: “Personalizar.”",
    text: "E agir antes.",
  },
  {
    slide: "Slide 14",
    title: "Dados em sinais",
    cue: "Nubya: “É utilizar o passado e o presente para tomar decisões melhores sobre o futuro.”",
    text: "É transformar dados em sinais.",
  },
  {
    slide: "Slide 14",
    title: "Antes que ele peça",
    cue: "Nubya: “Deveria começar quando percebemos que ele pode precisar de ajuda.”",
    text: "Antes mesmo que ele peça.",
  },
  {
    slide: "Final — Humor",
    title: "Tenho uma sugestão",
    cue: "Nubya: “Também acho.”",
    text: "Tenho uma sugestão.",
  },
  {
    slide: "Final — Humor",
    title: "Pesquisa de satisfação",
    cue: "Ana: “Lá vem.”",
    text: "Podemos fazer uma pesquisa de satisfação com o público.",
  },
  {
    slide: "Final — Humor",
    title: "Sim",
    cue: "Nubya: “Agora?”",
    text: "Sim.",
  },
  {
    slide: "Final — Humor",
    title: "Nome ainda não definido",
    cue: "Ana: “Elonora...”",
    text: "Meu nome ainda nem foi definido.",
  },
  {
    slide: "Frase final",
    title: "Fechamento (junto com Ana e Nubya)",
    cue: "Falado em conjunto com Ana e Nubya para encerrar",
    text: "CX Preditivo é parar de esperar o problema acontecer para começar a agir.",
  },
];
